using Newtonsoft.Json;

namespace MCWrapper.CLI.Connection
{
    /// <summary>
    /// This is the MultiChain response object
    /// </summary>
    public class CLIRequest
    {
        /// <summary>
        /// This is the MultiChain response object
        /// </summary>
        public CLIRequest()
        {
            Method = string.Empty;
            Params = new object[] { };
            Id = string.Empty;
            ChainName = string.Empty;
        }

        /// <summary>
        /// This is the MultiChain response object
        /// </summary>
        /// <param name="method"></param>
        /// <param name="params"></param>
        /// <param name="id"></param>
        /// <param name="chainName"></param>
        public CLIRequest(string method, object[] @params, string id, string chainName)
        {
            Method = method;
            Params = @params;
            Id = id;
            ChainName = chainName;
        }

        /// <summary>
        /// The blockchain method that were passed
        /// </summary>
        [JsonProperty(PropertyName = "method")]
        public string Method { get; set; }

        /// <summary>
        /// The params that were passed
        /// </summary>
        [JsonProperty(PropertyName = "_params")]
        public object[] Params { get; set; }

        /// <summary>
        /// Id values that was generated by the blockchain
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

        /// <summary>
        /// The blockchain name that was passed
        /// </summary>
        [JsonProperty(PropertyName = "chain_name")]
        public string ChainName { get; set; }
    }
}
